/* automatically generated by sparc-misc-auto.sh, do not edit! */

/* the register mapping: */
#define TME_SPARC_IREG_UNDEF		(-1)
#define TME_SPARC_IREG_G0		(0)
#define TME_SPARC_IREG_G1		(1)
#define TME_SPARC_IREG_G2		(2)
#define TME_SPARC_IREG_G3		(3)
#define TME_SPARC_IREG_G4		(4)
#define TME_SPARC_IREG_G5		(5)
#define TME_SPARC_IREG_G6		(6)
#define TME_SPARC_IREG_G7		(7)
#define TME_SPARC_IREG_PC		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 8)
#define TME_SPARC_IREG_PC_NEXT		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 9)
#define TME_SPARC_IREG_PC_NEXT_NEXT		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 10)
#define TME_SPARC_IREG_IMM		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 11)
#define TME_SPARC_IREG_Y		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 14)
#define TME_SPARC_IREG_FPX		(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 16)
#define tme_sparc32_ireg_psr		tme_sparc_ireg_uint32(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 20)
#define tme_sparc32_ireg_wim		tme_sparc_ireg_uint32(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 21)
#define tme_sparc32_ireg_tbr		tme_sparc_ireg_uint32(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 22)
#define tme_sparc64_ireg_tba		tme_sparc_ireg_uint64(((TME_SPARC_WINDOWS_MAX * 16) + 8) + 22)
#define tme_sparc64_ireg_pstate		tme_sparc_ireg_uint32((((TME_SPARC_WINDOWS_MAX * 16) + 8) + 23) << 1)
#define tme_sparc64_ireg_ccr		tme_sparc_ireg_uint8(((((TME_SPARC_WINDOWS_MAX * 16) + 8) + 24) << 3) + 0)
#define tme_sparc64_ireg_asi		tme_sparc_ireg_uint8(((((TME_SPARC_WINDOWS_MAX * 16) + 8) + 24) << 3) + 1)
/* automatically generated by sparc-insns-auto.sh, do not edit! */
_TME_RCSID("$Id: sparc-insns-auto.sh,v 1.5 2007/03/29 01:16:09 fredette Exp $");

TME_SPARC_FORMAT3_DECL(tme_sparc32_add, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_addcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sub, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_subcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_or, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_orcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_orn, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_orncc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_and, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_andcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_andn, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_andncc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_xor, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_xorcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_xnor, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_xnorcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_addx, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_addxcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_subx, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_subxcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_taddcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_taddcctv, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_tsubcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_tsubcctv, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_umul, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_umulcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_smul, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_smulcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_udiv, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_udivcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sdiv, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sdivcc, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sll, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_srl, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sra, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldb, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stb, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldh, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sth, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ld, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_st, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldd, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_std, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldstub, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldstuba, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_swap, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_swapa, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldba, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stba, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldha, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stha, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_lda, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_sta, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldda, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stda, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_jmpl, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldf, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_lddf, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_ldfsr, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stf, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stdf, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_stfsr, tme_uint32_t);
TME_SPARC_FORMAT3_DECL(tme_sparc32_mulscc, tme_uint32_t);
const tme_shared tme_uint8_t *tme_sparc32_load _TME_P((struct tme_sparc *, tme_uint32_t, unsigned int));
tme_shared tme_uint8_t *tme_sparc32_store _TME_P((struct tme_sparc *, tme_uint32_t, const tme_uint32_t *, unsigned int));
